let workList = [
  {
    name: "Gardener",
    low: 26.39,
    median: 27.23,
    high: 31.5,
    value: 1,
  },
  {
    name: "Dishwasher",
    low: 22.5,
    median: 24.36,
    high: 29.47,
    value: 2,
  },
  {
    name: "Construction Labourer",
    low: 27.38,
    median: 29.15,
    high: 34.78,
    value: 3,
  },
  {
    name: "Machine Operator",
    low: 27.15,
    median: 30.27,
    high: 37,
    value: 4,
  },
  {
    name: "Agricultural worker",
    low: 28.21,
    median: 39.62,
    high: 51.73,
    value: 5,
  },
  {
    name: "Bus Driver",
    low: 27.44,
    median: 30,
    high: 38.48,
    value: 6,
  },
  {
    name: "Delivery Driver",
    low: 25,
    median: 27.7,
    high: 32.53,
    value: 7,
  },
  {
    name: "Ware House Worker",
    low: 19.33,
    median: 25,
    high: 28,
    value: 8,
  },
  {
    name: "Assembler",
    low: 26.15,
    median: 28,
    high: 32.87,
    value: 9,
  },
  {
    name: "Hairstylist",
    low: 26,
    median: 27,
    high: 29.18,
    value: 10,
  },
  {
    name: "Cleaner",
    low: 25.09,
    median: 26.9,
    high: 30.55,
    value: 11,
  },
  {
    name: "Carpenter",
    low: 32.45,
    median: 37.89,
    high: 46.11,
    value: 12,
  },
  {
    name: "Electrician",
    low: 35.9,
    median: 41.94,
    high: 60.38,
    value: 13,
  },
  {
    name: "Machine Operator",
    low: 27.15,
    median: 30.27,
    high: 437,
    value: 14,
  },
  {
    name: "Taxi Driver",
    low: 31,
    median: 37.5,
    high: 44,
    value: 15,
  },
  {
    name: "Cashier",
    low: 30.26,
    median: 31.67,
    high: 35,
    value: 16,
  },
];
let visaList = [
  {
    name: "Student Visa (Subclass 500)",
    hours: "20",
    value: 1,
  },
  {
    name: "Parent visa (Subclass 103)",
    hours: "38",
    value: 2,
  },
  {
    name: "Partner visa (Temporary) (Subclass 820)",
    hours: "38",
    value: 3,
  },
  {
    name: "Partner visa (Permanent) (Subclass 801)",
    hours: "38",
    value: 4,
  },
  {
    name: "Refugee visas (Subclass 200,201,203 and 204)",
    hours: "38",
    value: 5,
  },
  {
    name: "Temporary Skill Shortage visa (subclass 482)",
    hours: "38",
    value: 6,
  },
  {
    name: "Global Talent visa (subclass 858)",
    hours: "38",
    value: 7,
  },
  {
    name: "Distinguished Talent visa (subclass 124)",
    hours: "38",
    value: 8,
  },
  {
    name: "Regional Sponsored Migration Scheme visa (subclass 494)",
    hours: "38",
    value: 9,
  },
  {
    name: "Skilled Employer Sponsored Regional (provisional) visa (subclass 494)",
    hours: "38",
    value: 10,
  },
];
